### ISSUE TITLE
BBox training 

### ISSUE THREAD

**Issue by Seleucia** [serre-lab/gala_tpu#2]
Hello i'm trying to test model with using bboxes, i'm a bit confused with the [create_bb](https://github.com/serre-lab/gala_tpu/blob/98efcf1bf3bc3b738d6c36c38a60952d8d830722/resnet_preprocessing.py#L164) function in resnet_preprocessing. It seems model  accept only BBox which start with '0' (ex: [0,0,50,50]).
For example this function is going to fail with BBox=[10,10,50,50].  Am I true?. If so, why do you think this way appropriate. An object be anywhere in the image?

**Comment by drewlinsley** [comment]
Hi, thanks for the comment. That function was created for an experiment I was going to run but never fully implemented on TPUs. Thanks for pointing my attention to it -- I will clean it up.
